package com.jianping.lee.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BLACK_NUM.
 */
public class BlackNum {

    private Long id;
    private String name;
    private String phone;
    private Integer mode;
    private Integer index;

    public BlackNum() {
    }

    public BlackNum(Long id) {
        this.id = id;
    }

    public BlackNum(Long id, String name, String phone, Integer mode, Integer index) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.mode = mode;
        this.index = index;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getMode() {
        return mode;
    }

    public void setMode(Integer mode) {
        this.mode = mode;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

}
