package com.jianping.lee.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCKED_APP.
 */
public class LockedApp {

    private Long id;
    private String packName;
    private String appName;

    public LockedApp() {
    }

    public LockedApp(Long id) {
        this.id = id;
    }

    public LockedApp(Long id, String packName, String appName) {
        this.id = id;
        this.packName = packName;
        this.appName = appName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackName() {
        return packName;
    }

    public void setPackName(String packName) {
        this.packName = packName;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

}
